import { StyleSheet } from "react-native";
import { fontFamilies } from "../constants/theme";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FDFCF8" },
  topBar: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", padding: 16, borderBottomWidth: 1, borderColor: "#EAE9E4" },
  topTitle: { fontFamily: fontFamilies.technicalBold, fontSize: 14, letterSpacing: 2 },
  topIcon: { fontSize: 20 },
  avatarMini: { width: 32, height: 32, borderRadius: 16, backgroundColor: "#1A1A1A", justifyContent: "center", alignItems: "center" },
  scrollContent: { padding: 16 },
  alertCard: { backgroundColor: "#FCE8E8", padding: 16, borderRadius: 12, marginBottom: 16 },
  alertTitle: { color: "#B3261E", fontFamily: fontFamilies.technicalBold, fontSize: 12, marginBottom: 8 },
  alertText: { color: "#B3261E", fontFamily: fontFamilies.body, fontSize: 12, lineHeight: 18 },
  heroCard: { backgroundColor: "#8C0000", padding: 24, borderRadius: 12, marginBottom: 16 },
  heroSub: { color: "rgba(255,255,255,0.7)", fontFamily: fontFamilies.technicalBold, fontSize: 10, letterSpacing: 1, marginBottom: 8 },
  heroTitle: { color: "#FFF", fontFamily: fontFamilies.headlineBold, fontSize: 28, marginBottom: 12 },
  heroText: { color: "rgba(255,255,255,0.9)", fontFamily: fontFamilies.body, fontSize: 14, lineHeight: 20, marginBottom: 20 },
  heroBtn: { backgroundColor: "#FFF", padding: 14, borderRadius: 8, alignItems: "center" },
  heroBtnText: { color: "#8C0000", fontFamily: fontFamilies.technicalBold, fontSize: 12, letterSpacing: 1 },
  grid: { flexDirection: "row", justifyContent: "space-between", marginBottom: 16 },
  gridItem: { flex: 1, backgroundColor: "#F4F3EF", padding: 16, borderRadius: 12, marginHorizontal: 4 },
  gridLabel: { fontFamily: fontFamilies.technicalBold, fontSize: 10, color: "#6A6A6A", marginBottom: 8 },
  gridValueBigger: { fontFamily: fontFamilies.headlineBold, fontSize: 32, color: "#1A1A1A" },
  gridValue: { fontFamily: fontFamilies.headlineBold, fontSize: 28, color: "#1A1A1A" },
  gridUnit: { fontSize: 14, fontFamily: fontFamilies.body },
  gridDesc: { fontFamily: fontFamilies.technicalBold, fontSize: 10, color: "#6A6A6A", marginTop: 8 },
  gridSubDesc: { fontFamily: fontFamilies.body, fontSize: 10, color: "#8A8A8A", fontStyle: 'italic' },
  progressBar: { height: 4, backgroundColor: "#EAE9E4", borderRadius: 2, marginTop: 8 },
  progressFill: { height: 4, backgroundColor: "#0055FF", borderRadius: 2 },
  highlightCard: { backgroundColor: "#2563EB", padding: 24, borderRadius: 12, marginBottom: 16 },
  highlightSub: { color: "rgba(255,255,255,0.8)", fontFamily: fontFamilies.technicalBold, fontSize: 10, letterSpacing: 1, marginBottom: 8 },
  highlightTitle: { color: "#FFF", fontFamily: fontFamilies.headlineBold, fontSize: 18, marginBottom: 24 },
  highlightValue: { color: "#FFF", fontFamily: fontFamilies.headlineBold, fontSize: 48 },
  highlightUnit: { fontSize: 18 },
  metricCard: { backgroundColor: "#FCE8E8", padding: 20, borderRadius: 12, marginBottom: 16 },
  metricLabel: { fontFamily: fontFamilies.technicalBold, fontSize: 10, color: "#6A6A6A", marginBottom: 4 },
  metricValue: { fontFamily: fontFamilies.headlineBold, fontSize: 24, color: "#1A1A1A" },
  metricTarget: { fontFamily: fontFamilies.body, fontSize: 18, color: "#1A1A1A" },
});