import { StyleSheet } from "react-native";
import { colors, fontFamilies } from "../constants/theme";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FDFCF8" },
  scrollContent: { padding: 24 },
  header: { marginBottom: 24 },
  tag: {
    backgroundColor: "#9E1B1B",
    color: "#FFF",
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 4,
    fontSize: 10,
    fontFamily: fontFamilies.technicalBold,
    letterSpacing: 1,
    borderRadius: 4,
    marginBottom: 16,
  },
  title: {
    fontSize: 40,
    fontFamily: fontFamilies.headlineBold,
    color: "#1A1A1A",
    marginBottom: 16,
    lineHeight: 44,
  },
  subtitle: {
    fontSize: 16,
    fontFamily: fontFamilies.body,
    color: "#4A4A4A",
    lineHeight: 24,
  },
  infoCard: {
    backgroundColor: "#F4F3EF",
    borderRadius: 12,
    padding: 20,
    marginBottom: 32,
  },
  infoRow: { flexDirection: "row", marginBottom: 16 },
  infoIcon: { fontSize: 20, marginRight: 12 },
  infoTextContainer: { flex: 1 },
  infoTitle: {
    fontSize: 12,
    fontFamily: fontFamilies.technicalBold,
    color: "#1A1A1A",
    marginBottom: 4,
  },
  infoDesc: {
    fontSize: 12,
    fontFamily: fontFamilies.body,
    color: "#6A6A6A",
    lineHeight: 18,
  },
  form: { flex: 1 },
  inputGroup: { marginBottom: 20 },
  row: { flexDirection: "row", justifyContent: "space-between" },
  label: {
    fontSize: 10,
    fontFamily: fontFamilies.technicalBold,
    color: "#6A6A6A",
    marginBottom: 8,
    letterSpacing: 1,
  },
  input: {
    backgroundColor: "#EAE9E4",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: fontFamilies.body,
    color: "#1A1A1A",
  },
  inputWithSuffix: {
    backgroundColor: "#EAE9E4",
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  inputNoBg: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 16,
    fontFamily: fontFamilies.body,
    color: "#1A1A1A",
  },
  suffix: {
    fontSize: 12,
    fontFamily: fontFamilies.technicalBold,
    color: "#1A1A1A",
  },
  selectInput: {
    backgroundColor: "#EAE9E4",
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  selectText: { fontSize: 16, color: "#1A1A1A", fontFamily: fontFamilies.body },
  selectIcon: { fontSize: 18, color: "#6A6A6A" },
  btnPrimary: {
    backgroundColor: "#9E1B1B",
    borderRadius: 12,
    paddingVertical: 18,
    alignItems: "center",
    marginTop: 10,
  },
  btnPrimaryText: {
    color: "#FFF",
    fontSize: 14,
    fontFamily: fontFamilies.technicalBold,
    letterSpacing: 2,
  },
  footerText: {
    textAlign: "center",
    fontSize: 10,
    color: "#8A8A8A",
    marginTop: 24,
    fontFamily: fontFamilies.technicalBold,
    lineHeight: 16,
  },
});