import { StyleSheet } from "react-native";
import { fontFamilies } from "../constants/theme";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FDFCF8" },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderColor: "#EAE9E4",
  },
  topTitle: {
    flex: 1,
    textAlign: "center",
    fontFamily: fontFamilies.technicalBold,
    fontSize: 14,
    letterSpacing: 2,
  },
  topIcon: { fontSize: 20 },
  avatarMini: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#ebe8e4",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarMiniText: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 13,
    color: "#2E2A25",
  },
  scrollContent: { padding: 16 },
  timerCard: {
    backgroundColor: "#FFF",
    padding: 24,
    borderRadius: 12,
    alignItems: "center",
    marginBottom: 16,
    elevation: 2,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  timerLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 10,
    color: "#6A6A6A",
    letterSpacing: 1,
    marginBottom: 8,
  },
  timerValue: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 48,
    color: "#2E2A25",
    marginBottom: 8,
  },
  statusActive: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 12,
    color: "#9E1B1B",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  statBox: {
    flex: 1,
    backgroundColor: "#FCE8E8",
    padding: 16,
    borderRadius: 12,
    marginHorizontal: 4,
  },
  statLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 10,
    color: "#6A6A6A",
    marginBottom: 8,
  },
  statValue: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 24,
    color: "#2E2A25",
  },
  statUnit: { fontSize: 14, fontFamily: fontFamilies.body },
  sectionTitle: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 12,
    color: "#6A6A6A",
    letterSpacing: 1,
    marginBottom: 12,
  },
  quickLogGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  quickLogBtnLight: {
    flex: 1,
    backgroundColor: "#FFF",
    padding: 20,
    borderRadius: 12,
    alignItems: "center",
    marginHorizontal: 4,
    borderWidth: 1,
    borderColor: "#EAE9E4",
  },
  quickLogBtnDark: {
    flex: 1,
    backgroundColor: "#8C0000",
    padding: 20,
    borderRadius: 12,
    alignItems: "center",
    marginHorizontal: 4,
  },
  quickLogIcon: { fontSize: 24, marginBottom: 8 },
  quickLogValueDark: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 24,
    color: "#1A1A1A",
  },
  quickLogDescDark: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 10,
    color: "#6A6A6A",
    marginTop: 4,
  },
  quickLogValueLight: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 24,
    color: "#FFF",
  },
  quickLogDescLight: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 10,
    color: "#FFF",
    marginTop: 4,
  },
  customLogBtn: {
    backgroundColor: "#FCE8E8",
    padding: 16,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 32,
  },
  customLogText: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 12,
    color: "#1A1A1A",
    letterSpacing: 1,
  },
  logHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  logCount: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 10,
    color: "#9E1B1B",
  },
  logItem: {
    flexDirection: "row",
    backgroundColor: "#FFF",
    padding: 16,
    borderRadius: 12,
    marginBottom: 12,
    alignItems: "center",
  },
  logIconWrapperRed: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: "#F69F9B",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  logTextWrapper: { flex: 1 },
  logItemTitle: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 14,
    color: "#1A1A1A",
  },
  logItemSub: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 10,
    color: "#8A8A8A",
    marginTop: 4,
  },
  logOptions: { fontSize: 20, color: "#D1D1D1", paddingHorizontal: 8 },
  endSessionBtn: {
    backgroundColor: "#8C0000",
    padding: 18,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 24,
    marginBottom: 32,
  },
  endSessionText: {
    color: "#FFF",
    fontFamily: fontFamilies.technicalBold,
    fontSize: 14,
    letterSpacing: 2,
  },
});
