import { colors, fontFamilies } from "@/constants/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  // Header
  header: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    borderBottomWidth: 1,
    borderBottomColor: `${colors.outlineVariant}30`,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  headerLogo: { flexDirection: "row", alignItems: "center", gap: 8 },
  headerBrand: {
    fontFamily: fontFamilies.headline,
    letterSpacing: 3,
    color: colors.onSurface,
    fontSize: 13,
    fontWeight: "300",
  },
  headerLinks: { flexDirection: "row", gap: 14 },
  headerLink: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 2,
    color: colors.onSurfaceVariant,
    textTransform: "uppercase",
  },

  // Hero
  hero: { height: 620, backgroundColor: "#111", justifyContent: "flex-end" },
  heroContent: { padding: 28, paddingBottom: 48, gap: 0 },
  heroTag: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 4,
    color: colors.primaryContainer,
    textTransform: "uppercase",
    marginBottom: 12,
  },
  heroTitle: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 38,
    fontWeight: "900",
    color: colors.white,
    lineHeight: 44,
    marginBottom: 28,
  },
  heroTitleLight: {
    fontFamily: fontFamilies.headlineItalic,
    fontStyle: "italic",
    fontWeight: "300",
    color: "rgba(252,249,245,0.85)",
  },
  heroActions: { gap: 16 },
  heroPrimaryBtn: {
    backgroundColor: colors.primary,
    borderRadius: 50,
    paddingHorizontal: 32,
    paddingVertical: 18,
    alignSelf: "flex-start",
  },
  heroPrimaryBtnText: {
    fontFamily: fontFamilies.technicalBold,
    color: colors.white,
    fontWeight: "700",
    fontSize: 11,
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  heroMeta: { flexDirection: "row", alignItems: "center" },
  heroMetaText: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 13,
    fontFamily: fontFamilies.body,
  },

  // Seção
  section: {
    backgroundColor: colors.surfaceContainerLow,
    paddingHorizontal: 20,
    paddingVertical: 36,
    gap: 18,
  },
  sectionTitle: {
    fontFamily: fontFamilies.headline,
    fontSize: 28,
    color: colors.onSurface,
    lineHeight: 34,
  },
  sectionSub: {
    fontFamily: fontFamilies.body,
    fontSize: 14,
    color: colors.onSurfaceVariant,
    lineHeight: 21,
  },

  // Card branco — Monitoramento
  cardWhite: {
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 22,
    gap: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardIconWrap: {
    backgroundColor: colors.surfaceContainerLow,
    padding: 10,
    borderRadius: 12,
  },
  badge: {
    backgroundColor: colors.surfaceContainerLow,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  badgeText: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 1.5,
    color: colors.onSurfaceVariant,
    textTransform: "uppercase",
  },
  cardTitle: {
    fontFamily: fontFamilies.headline,
    fontSize: 21,
    color: colors.onSurface,
  },
  cardBody: {
    fontFamily: fontFamilies.body,
    fontSize: 13,
    color: colors.onSurfaceVariant,
    lineHeight: 19,
  },
  statsRow: {
    flexDirection: "row",
    gap: 28,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
    marginTop: 4,
  },
  statNum: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 26,
    fontWeight: "700",
    color: colors.primary,
  },
  statLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 1.5,
    color: `${colors.onSurfaceVariant}80`,
    textTransform: "uppercase",
    marginTop: 2,
  },

  // Card azul — Precisão
  cardBlue: {
    backgroundColor: colors.secondary,
    borderRadius: 20,
    padding: 22,
    gap: 12,
  },
  cardBlueTitle: {
    fontFamily: fontFamilies.headline,
    fontSize: 24,
    color: colors.white,
    lineHeight: 30,
  },
  cardBlueBody: {
    fontFamily: fontFamilies.body,
    fontSize: 13,
    color: "rgba(255,255,255,0.8)",
    lineHeight: 19,
  },
  cardBlueLink: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 2,
    color: colors.white,
    textTransform: "uppercase",
    marginTop: 4,
  },

  // Card escuro — Lab
  cardDark: {
    backgroundColor: colors.onSurface,
    borderRadius: 20,
    padding: 22,
    gap: 12,
  },
  cardDarkTitle: {
    fontFamily: fontFamilies.headline,
    fontSize: 19,
    color: colors.white,
  },
  cardDarkPanel: {
    backgroundColor: "rgba(255,255,255,0.06)",
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    marginTop: 4,
  },
  cardDarkLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 8,
    fontWeight: "700",
    letterSpacing: 2,
    color: "rgba(255,255,255,0.4)",
    textTransform: "uppercase",
  },

  // Quote
  quoteCard: {
    height: 240,
    borderRadius: 18,
    overflow: "hidden",
    justifyContent: "flex-end",
    padding: 22,
  },
  quoteText: {
    fontFamily: fontFamilies.headlineItalic,
    fontSize: 18,
    fontStyle: "italic",
    color: colors.white,
    lineHeight: 26,
  },

  // Arquitetura de dados
  dataHeaderBar: {
    borderLeftWidth: 2,
    borderLeftColor: `${colors.primary}35`,
    paddingLeft: 14,
    marginBottom: 4,
  },
  dataTag: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 3,
    color: colors.primary,
    textTransform: "uppercase",
  },
  dataTitle: {
    fontFamily: fontFamilies.headline,
    fontSize: 32,
    color: colors.onSurface,
    lineHeight: 38,
    marginTop: 6,
  },
  dataTitleLight: { fontStyle: "italic", fontWeight: "300" },
  dataItem: {
    flexDirection: "row",
    gap: 14,
    alignItems: "flex-start",
    paddingVertical: 6,
  },
  dataNum: {
    fontFamily: fontFamilies.headlineItalic,
    fontSize: 36,
    fontStyle: "italic",
    color: `${colors.onSurface}14`,
    width: 52,
  },
  dataItemTitle: {
    fontFamily: fontFamilies.headline,
    fontSize: 19,
    color: colors.onSurface,
    marginBottom: 5,
  },
  dataItemBody: {
    fontFamily: fontFamilies.body,
    fontSize: 13,
    color: colors.onSurfaceVariant,
    lineHeight: 19,
  },
  dataPanel: {
    backgroundColor: colors.surfaceContainerHigh,
    borderRadius: 22,
    padding: 24,
    marginTop: 4,
  },
  panelSmallLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 9,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: `${colors.onSurfaceVariant}80`,
    fontWeight: "700",
  },
  panelBpm: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 64,
    fontWeight: "900",
    color: colors.onSurface,
  },
  panelBpmUnit: {
    fontFamily: fontFamilies.technical,
    fontSize: 14,
    letterSpacing: 3,
    textTransform: "uppercase",
    color: `${colors.onSurface}45`,
  },
  panelEff: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 17,
    fontWeight: "700",
    color: colors.primary,
    marginTop: 2,
  },

  // CTA
  ctaSection: {
    backgroundColor: colors.surfaceContainerHighest,
    paddingVertical: 60,
    paddingHorizontal: 28,
    alignItems: "center",
    gap: 28,
  },
  ctaTitle: {
    fontFamily: fontFamilies.headline,
    fontSize: 34,
    color: colors.onSurface,
    textAlign: "center",
    lineHeight: 42,
  },
  ctaTitleItalic: { fontStyle: "italic" },
  ctaBtn: {
    backgroundColor: colors.onSurface,
    borderRadius: 50,
    paddingHorizontal: 32,
    paddingVertical: 18,
  },
  ctaBtnText: {
    fontFamily: fontFamilies.technicalBold,
    color: colors.surface,
    fontWeight: "700",
    fontSize: 10,
    letterSpacing: 3,
    textTransform: "uppercase",
  },

  // Footer
  footer: {
    backgroundColor: colors.surfaceContainerLow,
    borderTopWidth: 1,
    borderTopColor: `${colors.outlineVariant}25`,
    padding: 28,
  },
  footerBrand: {
    fontFamily: fontFamilies.headlineItalic,
    fontSize: 16,
    fontStyle: "italic",
    fontWeight: "600",
    color: colors.onSurface,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  footerCopy: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 8,
    letterSpacing: 2,
    color: `${colors.onSurfaceVariant}70`,
    textTransform: "uppercase",
    fontWeight: "700",
    marginTop: 4,
  },
  footerLink: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 9,
    letterSpacing: 2,
    textTransform: "uppercase",
    fontWeight: "700",
    color: colors.onSurfaceVariant,
  },

  // Bottom Nav
  bottomNav: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-around",
    borderTopWidth: 1,
    borderTopColor: `${colors.primary}10`,
    paddingTop: 10,
    zIndex: 60,
  },
  navItem: {
    alignItems: "center",
    gap: 3,
    paddingHorizontal: 10,
    position: "relative",
  },
  navDot: {
    position: "absolute",
    top: -10,
    width: 28,
    height: 3,
    backgroundColor: colors.primary,
    borderRadius: 4,
  },
  navLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 8,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.5,
    color: `${colors.onSurfaceVariant}70`,
  },
});