import { StyleSheet } from "react-native";
import { colors, fontFamilies } from "../constants/theme";

export const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: colors.surface,
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontFamily: fontFamilies.technicalBold,
    fontSize: 14,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: colors.onSurface,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surfaceContainerHigh,
    alignItems: "center",
    justifyContent: "center",
  },
  headerAvatarText: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 14,
    letterSpacing: 1,
    color: colors.onSurface,
  },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 8 },
  divider: {
    height: 1,
    backgroundColor: colors.outlineVariant,
    marginVertical: 20,
  },
  sectionLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
    marginBottom: 14,
  },
  avatarSection: { alignItems: "center", paddingVertical: 20 },
  avatarWrapper: { position: "relative", marginBottom: 14 },
  avatarPlaceholder: {
    width: 90,
    height: 90,
    borderRadius: 12,
    backgroundColor: colors.onSurface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.primary,
  },
  avatarInitials: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 24,
    color: colors.white,
  },
  badgeOnline: {
    position: "absolute",
    bottom: -4,
    right: -4,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.success,
    borderWidth: 2,
    borderColor: colors.surface,
  },
  playerName: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 24,
    color: colors.onSurface,
    marginBottom: 4,
  },
  playerRole: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
    marginBottom: 14,
  },
  tagsRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    justifyContent: "center",
  },
  tag: {
    backgroundColor: colors.primaryTint,
    borderRadius: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
  },
  tagText: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 11,
    letterSpacing: 0.5,
    color: colors.primary,
    textTransform: "uppercase",
  },
  infoCard: {
    flexDirection: "row",
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: 10,
    marginBottom: 10,
    overflow: "hidden",
    shadowColor: colors.black,
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  infoAccent: { width: 4 },
  infoContent: { flex: 1, paddingHorizontal: 16, paddingVertical: 14 },
  infoLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
    marginBottom: 4,
  },
  infoValue: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 20,
    color: colors.onSurface,
    marginBottom: 2,
  },
  infoSub: {
    fontFamily: fontFamilies.technical,
    fontSize: 13,
    color: colors.onSurfaceVariant,
    lineHeight: 18,
  },
  configSection: {
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: 12,
    padding: 18,
    marginBottom: 4,
    shadowColor: colors.black,
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  rowSeparator: {
    height: 1,
    backgroundColor: colors.outlineVariant,
    marginVertical: 14,
  },
  especRow: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  especDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.primary,
    marginTop: 6,
  },
  especTexts: { flex: 1 },
  especTitle: {
    fontFamily: fontFamilies.bodyBold,
    fontSize: 15,
    color: colors.onSurface,
    marginBottom: 3,
  },
  especDetail: {
    fontFamily: fontFamilies.technical,
    fontSize: 13,
    color: colors.onSurfaceVariant,
    lineHeight: 18,
  },
  statCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: 10,
    padding: 16,
    marginBottom: 10,
    shadowColor: colors.black,
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  statIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: colors.surfaceContainerHigh,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  statEmoji: { fontSize: 20 },
  statLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
    marginBottom: 2,
  },
  statValue: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 28,
    color: colors.onSurface,
  },
  statUnit: {
    fontFamily: fontFamilies.body,
    fontSize: 14,
    color: colors.onSurfaceVariant,
  },
  btnPrimary: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 12,
  },
  btnPrimaryText: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.white,
  },
  btnSecondary: {
    borderWidth: 1.5,
    borderColor: colors.outlineVariant,
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: "center",
  },
  btnSecondaryText: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurface,
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: colors.surfaceContainerLow,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
    paddingVertical: 8,
    paddingBottom: 12,
  },
  tabItem: { flex: 1, alignItems: "center", justifyContent: "center" },
  tabIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  tabIconActive: { backgroundColor: colors.primary },
  tabIcon: { fontSize: 16 },
  tabLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 9,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
  },
  tabLabelActive: { color: colors.primary },
  infoInput: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 18,
    color: colors.onSurface,
    borderBottomWidth: 1.5,
    borderBottomColor: colors.primary,
    paddingVertical: 4,
    marginBottom: 4,
  },
  infoInputSub: {
    fontFamily: fontFamilies.technical,
    fontSize: 13,
    color: colors.onSurfaceVariant,
    borderBottomWidth: 1,
    borderBottomColor: colors.outlineVariant,
    paddingVertical: 2,
    lineHeight: 18,
  },
});
