// src/styles/ProfileStyle.ts
import { StyleSheet } from "react-native";
import { colors, fontFamilies } from "../constants/theme";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 14,
    backgroundColor: colors.surface,
  },
  headerMenu: {
    fontSize: 20,
    color: colors.onSurface,
  },
  headerTitle: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 14,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: colors.onSurface,
  },
  headerBrand: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 14,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.primary,
  },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingTop: 8 },
  divider: {
    height: 1,
    backgroundColor: colors.outlineVariant,
    marginVertical: 20,
  },
  sectionLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
    marginBottom: 14,
  },
  avatarSection: {
    alignItems: "center",
    paddingVertical: 20,
  },
  avatarWrapper: {
    position: "relative",
    marginBottom: 14,
  },
  avatarPlaceholder: {
    width: 90,
    height: 90,
    borderRadius: 12,
    backgroundColor: colors.onSurface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.primary,
  },
  avatarInitials: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 24,
    color: colors.white,
  },
  avatarEditButton: {
    position: "absolute",
    bottom: -6,
    right: -6,
    backgroundColor: colors.primary,
    width: 26,
    height: 26,
    borderRadius: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarEditIcon: { fontSize: 12 },
  playerName: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 24,
    color: colors.onSurface,
    marginBottom: 4,
  },
  playerRole: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
  },
  biometricCard: {
    flexDirection: "row",
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: 10,
    marginBottom: 10,
    overflow: "hidden",
    shadowColor: colors.black,
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  biometricAccent: { width: 4 },
  biometricContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  biometricLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
    marginBottom: 4,
  },
  biometricValue: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 32,
    color: colors.onSurface,
  },
  biometricUnit: {
    fontFamily: fontFamilies.body,
    fontSize: 16,
    color: colors.onSurfaceVariant,
  },
  configSection: {
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: 12,
    padding: 18,
    marginBottom: 4,
    shadowColor: colors.black,
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 4,
  },
  settingText: { flex: 1, marginRight: 16 },
  settingTitle: {
    fontFamily: fontFamilies.body,
    fontSize: 16,
    fontWeight: "600",
    color: colors.onSurface,
    marginBottom: 2,
  },
  settingSubtitle: {
    fontFamily: fontFamilies.technical,
    fontSize: 14,
    color: colors.onSurfaceVariant,
  },
  settingRowSeparator: {
    height: 1,
    backgroundColor: colors.outlineVariant,
    marginVertical: 14,
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  metaValue: {
    fontFamily: fontFamilies.body,
    fontSize: 16,
    fontWeight: "700",
    color: colors.primary,
  },
  sliderTrack: {
    height: 4,
    backgroundColor: colors.outlineVariant,
    borderRadius: 2,
    position: "relative",
    marginBottom: 6,
  },
  sliderFill: {
    height: 4,
    backgroundColor: colors.primary,
    borderRadius: 2,
  },
  sliderThumb: {
    position: "absolute",
    top: -6,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.primary,
  },
  sliderLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sliderLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
  },
  performanceCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: 10,
    padding: 16,
    marginBottom: 10,
    shadowColor: colors.black,
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  performanceIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: colors.surfaceContainerHigh,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
  },
  performanceEmoji: { fontSize: 20 },
  performanceLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
    marginBottom: 2,
  },
  performanceValue: {
    fontFamily: fontFamilies.headlineBold,
    fontSize: 32,
    color: colors.onSurface,
  },
  performanceUnit: {
    fontFamily: fontFamilies.body,
    fontSize: 16,
    color: colors.onSurfaceVariant,
  },
  btnPrimary: {
    backgroundColor: colors.primary,
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: "center",
    marginBottom: 12,
  },
  btnPrimaryText: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.white,
  },
  btnSecondary: {
    borderWidth: 1.5,
    borderColor: colors.outlineVariant,
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: "center",
  },
  btnSecondaryText: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurface,
  },
  tabBar: {
    flexDirection: "row",
    backgroundColor: colors.surfaceContainerLow,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
    paddingVertical: 8,
    paddingBottom: 12,
  },
  tabItem: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  tabIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 2,
  },
  tabIconActive: {
    backgroundColor: colors.primary,
  },
  tabIcon: { fontSize: 16 },
  tabLabel: {
    fontFamily: fontFamilies.technicalBold,
    fontSize: 9,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.onSurfaceVariant,
  },
  tabLabelActive: {
    color: colors.primary,
  },
});
